// <auto-generated />
using System;
using IchigoHoshimiya.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IchigoHoshimiya.Migrations
{
    [DbContext(typeof(IchigoContext))]
    [Migration("20260325215549_AddScrimWeapons")]
    partial class AddScrimWeapons
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringAnime", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AnilistId")
                        .HasColumnType("bigint")
                        .HasColumnName("anilist_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("varchar(10000)")
                        .HasColumnName("anime_title");

                    b.HasKey("Id");

                    b.ToTable("airing_anime");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringEpisode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("AiringAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("airing_at_utc");

                    b.Property<long>("AnimeId")
                        .HasColumnType("bigint")
                        .HasColumnName("anime_id");

                    b.Property<int>("EpisodeNumber")
                        .HasColumnType("int")
                        .HasColumnName("episode_number");

                    b.HasKey("Id");

                    b.HasIndex("AiringAtUtc");

                    b.HasIndex("AnimeId");

                    b.ToTable("airing_episode");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.GrassToucher", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("TouchingGrassUntilUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("touching_grass_until_utc");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("GrassToucher");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.RssReminder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Mentions")
                        .HasColumnType("longtext")
                        .HasColumnName("mentions");

                    b.Property<string>("SearchString")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("search_string");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedById");

                    b.ToTable("rss_reminder");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.ScrimSignup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("channel_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at_utc");

                    b.Property<ulong>("CreatedById")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_open");

                    b.Property<ulong?>("MessageId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("message_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("CreatedById");

                    b.HasIndex("MessageId")
                        .IsUnique();

                    b.ToTable("scrim_signup");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.ScrimSignupEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("AvailableDays")
                        .HasColumnType("int")
                        .HasColumnName("available_days");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<long>("ScrimSignupId")
                        .HasColumnType("bigint")
                        .HasColumnName("scrim_signup_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at_utc");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.Property<int>("Weapon")
                        .HasColumnType("int")
                        .HasColumnName("weapon");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ScrimSignupId", "UserId")
                        .IsUnique();

                    b.ToTable("scrim_signup_entry");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.TicketMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("AttachmentUrls")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<ulong>("AuthorId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("DiscordMessageId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetime");

                    b.Property<int>("TrackedTicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("DiscordMessageId");

                    b.HasIndex("TrackedTicketId");

                    b.HasIndex("ChannelId", "DiscordMessageId")
                        .IsUnique();

                    b.ToTable("TicketMessages");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.TrackedTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("ChannelId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("LastSyncedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("TicketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId")
                        .IsUnique();

                    b.ToTable("TrackedTickets");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringEpisode", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.AniList.AiringAnime", "Anime")
                        .WithMany("AiringEpisodes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.ScrimSignupEntry", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.General.ScrimSignup", "ScrimSignup")
                        .WithMany("Entries")
                        .HasForeignKey("ScrimSignupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScrimSignup");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.TicketMessage", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.General.TrackedTicket", "TrackedTicket")
                        .WithMany("Messages")
                        .HasForeignKey("TrackedTicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackedTicket");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.AniList.AiringAnime", b =>
                {
                    b.Navigation("AiringEpisodes");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.ScrimSignup", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.General.TrackedTicket", b =>
                {
                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
