// <auto-generated />
using System;
using IchigoHoshimiya.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IchigoHoshimiya.Migrations.Wwm
{
    [DbContext(typeof(WwmDbContext))]
    partial class WwmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmGear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int?>("Durability")
                        .HasColumnType("int")
                        .HasColumnName("durability");

                    b.Property<int?>("ItemIndex")
                        .HasColumnType("int")
                        .HasColumnName("item_index");

                    b.Property<long>("ItemNo")
                        .HasColumnType("bigint")
                        .HasColumnName("item_no");

                    b.Property<DateTime?>("RetoneAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("retone_at_utc");

                    b.Property<int?>("RetoneCount")
                        .HasColumnType("int")
                        .HasColumnName("retone_count");

                    b.Property<long?>("RetoneNo")
                        .HasColumnType("bigint")
                        .HasColumnName("retone_no");

                    b.Property<bool>("Retoned")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("retoned");

                    b.Property<string>("SlotName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("slot_name");

                    b.Property<int>("SlotOrd")
                        .HasColumnType("int")
                        .HasColumnName("slot_ord");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    b.Property<int?>("Suit")
                        .HasColumnType("int")
                        .HasColumnName("suit");

                    b.Property<string>("SuitName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("suit_name");

                    b.HasKey("Id");

                    b.HasIndex("ItemNo");

                    b.HasIndex("SuitName");

                    b.HasIndex("SnapshotId", "SlotOrd")
                        .IsUnique();

                    b.ToTable("wwm_gear");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmGearAffix", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<bool?>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<long>("AffixId")
                        .HasColumnType("bigint")
                        .HasColumnName("affix_id");

                    b.Property<string>("DisplayValue")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("display_value");

                    b.Property<long>("GearId")
                        .HasColumnType("bigint")
                        .HasColumnName("gear_id");

                    b.Property<string>("Name")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<string>("Type")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("type");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("AffixId");

                    b.HasIndex("Type");

                    b.HasIndex("GearId", "Ordinal")
                        .IsUnique();

                    b.ToTable("wwm_gear_affix");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmGearBaseAttr", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("GearId")
                        .HasColumnType("bigint")
                        .HasColumnName("gear_id");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<string>("RawName")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("raw_name");

                    b.Property<double>("Value")
                        .HasColumnType("double")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RawName");

                    b.HasIndex("GearId", "Ordinal")
                        .IsUnique();

                    b.ToTable("wwm_gear_base_attr");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmGearRetone", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("GearId")
                        .HasColumnType("bigint")
                        .HasColumnName("gear_id");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<long>("RetoneNo")
                        .HasColumnType("bigint")
                        .HasColumnName("retone_no");

                    b.HasKey("Id");

                    b.HasIndex("GearId", "Ordinal")
                        .IsUnique();

                    b.ToTable("wwm_gear_retone");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmPlayer", b =>
                {
                    b.Property<long>("NumberId")
                        .HasColumnType("bigint")
                        .HasColumnName("number_id");

                    b.Property<DateTime?>("AccountCreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("account_created_at_utc");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("FirstSeenAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("first_seen_at_utc");

                    b.Property<DateTime>("LastSeenAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Region")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("region");

                    b.Property<int>("Server")
                        .HasColumnType("int")
                        .HasColumnName("server");

                    b.HasKey("NumberId");

                    b.HasIndex("ExternalId");

                    b.HasIndex("Name");

                    b.ToTable("wwm_player");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmPlayerSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AccountCreatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("account_created_at_utc");

                    b.Property<int?>("ArenaRank")
                        .HasColumnType("int")
                        .HasColumnName("arena_rank");

                    b.Property<string>("BuildHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("build_hash");

                    b.Property<int?>("BuildPower")
                        .HasColumnType("int")
                        .HasColumnName("build_power");

                    b.Property<int?>("CelestialPulls")
                        .HasColumnType("int")
                        .HasColumnName("celestial_pulls");

                    b.Property<string>("ClubId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("club_id");

                    b.Property<string>("CurrentScenarioJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("current_scenario_json");

                    b.Property<DateTime?>("DataUpdatedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_updated_at_utc");

                    b.Property<ulong?>("DiscordAccountId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("discord_account_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("external_id");

                    b.Property<DateTime>("FetchedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fetched_at_utc");

                    b.Property<string>("GameplayTrailJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("gameplay_trail_json");

                    b.Property<string>("GuildName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("guild_name");

                    b.Property<int?>("HarmonicPulls")
                        .HasColumnType("int")
                        .HasColumnName("harmonic_pulls");

                    b.Property<bool>("HasPvpData")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("has_pvp_data");

                    b.Property<bool>("IsMaster")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_master");

                    b.Property<bool?>("IsOnline")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_online");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<DateTime?>("LoginAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("login_at_utc");

                    b.Property<DateTime?>("LogoutAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("logout_at_utc");

                    b.Property<string>("LookupJobId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("lookup_job_id");

                    b.Property<string>("LookupQuery")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("lookup_query");

                    b.Property<int>("LookupType")
                        .HasColumnType("int")
                        .HasColumnName("lookup_type");

                    b.Property<int?>("Losses")
                        .HasColumnType("int")
                        .HasColumnName("losses");

                    b.Property<string>("LunjianGrade")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("lunjian_grade");

                    b.Property<int?>("LunjianMaxStreak")
                        .HasColumnType("int")
                        .HasColumnName("lunjian_max_streak");

                    b.Property<string>("LunjianSmallGrade")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("lunjian_small_grade");

                    b.Property<int?>("LunjianTotal")
                        .HasColumnType("int")
                        .HasColumnName("lunjian_total");

                    b.Property<int?>("MainWeaponId")
                        .HasColumnType("int")
                        .HasColumnName("main_weapon_id");

                    b.Property<string>("MainWeaponName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("main_weapon_name");

                    b.Property<double?>("MaxWuwoScore")
                        .HasColumnType("double")
                        .HasColumnName("max_wuwo_score");

                    b.Property<int?>("MaxXiuweiKungfu")
                        .HasColumnType("int")
                        .HasColumnName("max_xiuwei_kungfu");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<long>("NumberId")
                        .HasColumnType("bigint")
                        .HasColumnName("number_id");

                    b.Property<double?>("OnlineTimeSeconds")
                        .HasColumnType("double")
                        .HasColumnName("online_time_seconds");

                    b.Property<int?>("OtherLegendPulls")
                        .HasColumnType("int")
                        .HasColumnName("other_legend_pulls");

                    b.Property<string>("OverseaTag")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("oversea_tag");

                    b.Property<string>("PvpGrade")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("pvp_grade");

                    b.Property<string>("PvpMaxGrade")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("pvp_max_grade");

                    b.Property<string>("PvpMaxSmallGrade")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("pvp_max_small_grade");

                    b.Property<int?>("PvpScore")
                        .HasColumnType("int")
                        .HasColumnName("pvp_score");

                    b.Property<int?>("PvpSeasonId")
                        .HasColumnType("int")
                        .HasColumnName("pvp_season_id");

                    b.Property<string>("PvpSmallGrade")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("pvp_small_grade");

                    b.Property<string>("RawBaseJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_base_json");

                    b.Property<string>("Region")
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("region");

                    b.Property<int?>("School")
                        .HasColumnType("int")
                        .HasColumnName("school");

                    b.Property<int>("Server")
                        .HasColumnType("int")
                        .HasColumnName("server");

                    b.Property<int?>("SolemnPulls")
                        .HasColumnType("int")
                        .HasColumnName("solemn_pulls");

                    b.Property<int?>("SubWeaponId")
                        .HasColumnType("int")
                        .HasColumnName("sub_weapon_id");

                    b.Property<string>("SubWeaponName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sub_weapon_name");

                    b.Property<int?>("SurfaceScore")
                        .HasColumnType("int")
                        .HasColumnName("surface_score");

                    b.Property<int?>("TotalMatches")
                        .HasColumnType("int")
                        .HasColumnName("total_matches");

                    b.Property<bool>("WasCached")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("was_cached");

                    b.Property<bool>("WasStale")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("was_stale");

                    b.Property<double?>("WinRate")
                        .HasColumnType("double")
                        .HasColumnName("win_rate");

                    b.Property<double?>("WinRatePercent")
                        .HasColumnType("double")
                        .HasColumnName("win_rate_percent");

                    b.Property<int?>("WinningStreak")
                        .HasColumnType("int")
                        .HasColumnName("winning_streak");

                    b.Property<int?>("Wins")
                        .HasColumnType("int")
                        .HasColumnName("wins");

                    b.HasKey("Id");

                    b.HasIndex("FetchedAtUtc");

                    b.HasIndex("GuildName");

                    b.HasIndex("LookupJobId");

                    b.HasIndex("NumberId", "BuildHash");

                    b.HasIndex("NumberId", "FetchedAtUtc")
                        .IsUnique();

                    b.ToTable("wwm_player_snapshot");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmSnapshotSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<int>("Slot")
                        .HasColumnType("int")
                        .HasColumnName("slot");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("SnapshotId", "Slot")
                        .IsUnique();

                    b.ToTable("wwm_snapshot_skill");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmSnapshotXinfa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasColumnName("ordinal");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("bigint")
                        .HasColumnName("snapshot_id");

                    b.Property<int>("XinfaId")
                        .HasColumnType("int")
                        .HasColumnName("xinfa_id");

                    b.HasKey("Id");

                    b.HasIndex("XinfaId");

                    b.HasIndex("SnapshotId", "Ordinal")
                        .IsUnique();

                    b.ToTable("wwm_snapshot_xinfa");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmTrackedPlayer", b =>
                {
                    b.Property<long>("NumberId")
                        .HasColumnType("bigint")
                        .HasColumnName("number_id");

                    b.Property<DateTime>("AddedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("added_at_utc");

                    b.Property<ulong>("AddedById")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("added_by_id");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("LastBuildChangeAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_build_change_at_utc");

                    b.Property<DateTime?>("LastCheckedAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_checked_at_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("last_error");

                    b.Property<DateTime?>("LastSuccessAtUtc")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_success_at_utc");

                    b.HasKey("NumberId");

                    b.HasIndex("Enabled");

                    b.HasIndex("LastCheckedAtUtc");

                    b.ToTable("wwm_tracked_player");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmGear", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.Wwm.WwmPlayerSnapshot", "Snapshot")
                        .WithMany("Gear")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmGearAffix", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.Wwm.WwmGear", "Gear")
                        .WithMany("Affixes")
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gear");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmGearBaseAttr", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.Wwm.WwmGear", "Gear")
                        .WithMany("BaseAttrs")
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gear");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmGearRetone", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.Wwm.WwmGear", "Gear")
                        .WithMany("RetoneHistory")
                        .HasForeignKey("GearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gear");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmPlayerSnapshot", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.Wwm.WwmPlayer", "Player")
                        .WithMany("Snapshots")
                        .HasForeignKey("NumberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmSnapshotSkill", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.Wwm.WwmPlayerSnapshot", "Snapshot")
                        .WithMany("Skills")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmSnapshotXinfa", b =>
                {
                    b.HasOne("IchigoHoshimiya.Entities.Wwm.WwmPlayerSnapshot", "Snapshot")
                        .WithMany("Xinfa")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmGear", b =>
                {
                    b.Navigation("Affixes");

                    b.Navigation("BaseAttrs");

                    b.Navigation("RetoneHistory");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmPlayer", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("IchigoHoshimiya.Entities.Wwm.WwmPlayerSnapshot", b =>
                {
                    b.Navigation("Gear");

                    b.Navigation("Skills");

                    b.Navigation("Xinfa");
                });
#pragma warning restore 612, 618
        }
    }
}
